name: Unit tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    environment: codacy_env
    runs-on: ubuntu-latest

    env:
      CODACY_PROJECT_TOKEN: ${{ secrets.CODACY_PROJECT_TOKEN }}

    strategy:
      matrix:
        pnpm-version: [6.0.2]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: use pnpm ${{ matrix.pnpm-version }}
        uses: pnpm/action-setup@v2
        with:
          version: ${{ matrix.pnpm-version }}

      - name: install dependencies and test
        run: pnpm i --frozen-lockfile

      - name: running tests and generate coverage
        run: pnpm run test:coverage

      - name: up coverage to codacy
        run: bash <(curl -Ls https://coverage.codacy.com/get.sh) report -r ./coverage/lcov.info
